### ISSUE TITLE
Upload your hard work!

### ISSUE THREAD

**Issue by dmadisetti** [katdho/road_graphembedding#1]
Just a thought, you should upload the code that goes with this. Example:

![image](https://user-images.githubusercontent.com/2689338/127927491-4a5d92c6-b08f-4382-bb70-db4490741e8d.png)

**Comment by hokathyd** [comment]
Dear Dylan,
Alright, just did it. Thanks for showing me a picture of how to do it, and
following me on Github. I followed you back as well and will see if I can
add a bio sometime soon haha.
Thanks!
Sincerely, Kathy.
